### ISSUE TITLE
Startup crash - Error during initialization

### ISSUE THREAD

**Issue by r2rX** [UCyborg/BerserkerQuake2#7]
Just compiled the latest snapshot and tried running it. An error dialogue box opens stating 'Error during initialization'. Running the executable in a terminal doesn't reveal any other information. The last version I tried, compiled over a week ago, works fine.

Compiled in Ubuntu 16.04 32bit & tested in Ubuntu 16.10 64bit w/ NVIDIA 375.20

Lemme know how I can help troubleshoot, if you'd like/need.

**Comment by UCyborg** [comment]
I've amended old commits few times so you may have not gotten all the changes. Try re-downloading the whole repository again. Oh, the binaries are now called berserkerq2 and game.so. Make sure you put game.so in baseq2 folder.

I think most errors don't show up in terminal because those functions that handle exact error messages only copy them in in-game console buffer, but not to the stdout. Something to look into.

**Comment by r2rX** [comment]
..... the facepalm is strong with this one.

I forgot to place the game.so file in the baseq2 folder. It's working perfectly now.
